/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false server/types/worker-configuration.d.ts` (hash: 4294df259f3a88ca798b229421c70abd)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	SOURCE_API_URL: "https://rangerbook.warmycat.com/res/Rangers_data.json";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SOURCE_API_URL">> {}
}
